quarkus.application.name=participation-service
quarkus.http.port=8083

quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.datasource.jdbc.url=jdbc:h2:file:./target/participation-service;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=false

%dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:participation-service-dev;DB_CLOSE_DELAY=-1
%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create

quarkus.rest-client.user-service.url=http://localhost:8081
quarkus.rest-client.action-service.url=http://localhost:8082

quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui

volunteer.notifications.enabled=true

%test.quarkus.http.test-port=0
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:participation-service-test;DB_CLOSE_DELAY=-1
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
