####
# Native image for participation-service.
#
# Build the native runner first:
# ./mvnw package -Dnative
#
# Build the image:
# docker build -f src/main/docker/Dockerfile.native -t volunteer/participation-service-native .
#
# Run:
# docker run -i --rm -p 8083:8083 volunteer/participation-service-native
####
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.4

WORKDIR /work/

RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work

COPY --chown=1001:root target/*-runner /work/application

EXPOSE 8083
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
