####
# JVM-mode image for user-service.
#
# Build the application first:
# ./mvnw package
#
# Build the image:
# docker build -f src/main/docker/Dockerfile.jvm -t volunteer/user-service-jvm .
#
# Run:
# docker run -i --rm -p 8081:8081 volunteer/user-service-jvm
####
FROM eclipse-temurin:21-jre

WORKDIR /deployments

COPY target/quarkus-app/lib/ ./lib/
COPY target/quarkus-app/*.jar ./
COPY target/quarkus-app/app/ ./app/
COPY target/quarkus-app/quarkus/ ./quarkus/

EXPOSE 8081

ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

ENTRYPOINT ["sh", "-c", "exec java $JAVA_OPTS_APPEND -jar quarkus-run.jar"]
