quarkus.application.name=action-service
quarkus.http.port=8082

quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.datasource.jdbc.url=jdbc:h2:file:./target/action-service;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=false

%dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:action-service-dev;DB_CLOSE_DELAY=-1
%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create

quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui

quarkus.rest-client.user-service.url=http://localhost:8081
quarkus.rest-client.participation-service.url=http://localhost:8083

volunteer.actions.default-category=community

%test.quarkus.http.test-port=0
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:action-service-test;DB_CLOSE_DELAY=-1
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
