quarkus.application.name=user-service
quarkus.http.port=8081

quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=sa

quarkus.datasource.jdbc.url=jdbc:h2:mem:user-service;DB_CLOSE_DELAY=-1

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql

quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui

quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4317
quarkus.otel.resource.attributes=service.name=user-service
quarkus.datasource.jdbc.telemetry=true
quarkus.smallrye-metrics.path=/metrics

quarkus.container-image.group=volunteer
quarkus.container-image.name=user-service
quarkus.container-image.tag=1.0.0

volunteer.password.min-length=6
volunteer.simulation.delay-ms=0
volunteer.simulation.failure-rate=0

%test.quarkus.http.test-port=0
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:user-service-test;DB_CLOSE_DELAY=-1
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.hibernate-orm.sql-load-script=no-file
%test.quarkus.otel.enabled=false
